services:
  weather-db:
    image: mongo:latest
    container_name: weather-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=user
    ports:
      - "27017:27017"

  weather-tools:
    build:
      context: ./tools
      dockerfile: Dockerfile
    image: weather-tools
    container_name: weather-tools
    volumes:
      - ./tools/data:/data
    depends_on:
      - weather-db

  weather-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: weather-api
    container_name: weather-api
    environment:
      - MONGO_URI=mongodb://user:user@geomongo:27017/us?authSource=admin
    ports:
      - "8000:8000"
    depends_on:
      - weather-db
