services:
  city-coordinates-db:
    image: mongo:latest
    container_name: city-coordinates-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=user
    ports:
      - "27017:27017"

  city-coordinates-tools:
    build:
      context: ./tools
      dockerfile: Dockerfile
    image: city-coordinates-tools
    container_name: city-coordinates-tools
    volumes:
      - ./tools/data:/data
    depends_on:
      - city-coordinates-db

  # city-coordinates-api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   image: city-coordinates-api
  #   container_name: city-coordinates-api
  #   environment:
  #     - MONGO_URI=mongodb://user:user@geomongo:27017/us?authSource=admin
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - city-coordinates-db

