services:
  city-search-db:
    image: mongo:latest
    container_name: city-search-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=user
    ports:
      - "27017:27017"

  city-search-tools:
    build:
      context: ./tools
      dockerfile: Dockerfile
    image: city-search-tools
    container_name: city-search-tools
    volumes:
      - ./tools/data:/data
    depends_on:
      - city-search-db

  city-search-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: weather-api
    container_name: city-search-api
    environment:
      - MONGO_URI=mongodb://user:user@geomongo:27017/us?authSource=admin
    ports:
      - "8000:8000"
    depends_on:
      - city-search-db
